spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels_db
    username: postgres
    password: matichelo17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  cloud:
#    config:
#      name: service-hotel # busca la configuración de manera explicita para el servicio de hotel
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: ${EUREKA_SERVER:http://localhost:9001}/eureka
